# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbc5fccbc1513cd8305fb130033f2f8a813d129affb7730063ac7bdf01f0567728b285e2be14b35fb522ef0f0e06ffcf5b98f58a7a525928417924410a0eaee8

test:
  secret_key_base: 4005d824a94859f87d80306ecfe9cd9ad2e3deb9312a9ac2a0881c152d59c8a4b971ed483fc4c9f62190f25764d33bed0eda8825d24c27acf75ca5d80b10eb1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
